model_selection: 'server_resnet50'

server_resnet50:
  pretrained: True 
  input_size: 224
  freeze_backbone: True 
  num_classes: 2

custom_cnn:
  input_size: 224
  hidden_layers: [32,64, 128]
  dropout: 0.3
  num_classes: 2

training:
  batch_size: 16
  learning_rate: 0.001
  num_epochs: 10
  device: 'cuda'
  num_worker: 4

model_weight:
 model_path: 'weights/model.pt'